server:
  port: 8082

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:sqlite:./db/gimnasio_prod.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false