server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:sqlite:./db/gimnasio_dev.db?foreign_keys=true&journal_mode=WAL&busy_timeout=5000
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate.format_sql: true
      # Genera el archivo .sql externo
      jakarta.persistence.schema-generation.scripts.action: create
      jakarta.persistence.schema-generation.scripts.create-target: ./db/gimnasio-dev.sql
      # Obliga a crear las tablas en la base de datos SQLite activa
      jakarta.persistence.schema-generation.database.action: create-drop
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql