server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:sqlite:./db/gimnasio_dev.db?foreign_keys=true&journal_mode=WAL&busy_timeout=5000
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update #$$$IMPORTANTE$$$
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate.format_sql: true
      # Eliminamos 'jakarta.persistence.schema-generation.database.action: create-drop'
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
    com.backend.megatlon: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

# Agregar al final de application-dev.yaml
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 horas en milisegundos